//////////////////////////////////////////////////////////////////////
// Stingray Software - Objective Chart(tm) Copyright (c) 1996 Stingray
// Software Inc. All Rights Reserved. This source code is only
// intended as a supplement to the Stingray Objective Chart product.
// See the help files for detailed information regarding the use of these classes
/////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////
// The text comments in this file are formatted to generate
// a help file on build using Microsoft's free Autoduck tool.
// The help file is available with this source and it is
// recommended that you use this file in conjunction with the
// mfc help files.
/////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////
//@doc SRGCompoundDisplay
//@module SRGCply.h | SRGCompiledPolygon class declaration file<nl>
//Includes SRGCoordinate class<nl>
//Copyright <cp>Stingray Software 1996<nl>
//Written by Bob Powell (www.stingray.com)

//$head Utility classes
//$level 1


#ifdef _OBJCHART_DLL
	#undef AFXAPP_DATA
	#define AFXAPP_DATA AFXAPI_DATA
	#undef AFX_DATA
	#define AFX_DATA OC_DATA
#endif


#ifndef __SRGCOMPILEDPOLYGON__
#define __SRGCOMPILEDPOLYGON__

/////////////////////////////////////////////
// Autoduck comment block for SRGCoordinate

//@mdata float | SRGCoordinate | x | Floating point X coordinate value

//@mdata float | SRGCoordinate | y | Floating point Y coordinate value

//@mfunc 	| SRGCoordinate |SRGCoordinate | Initializing constructor -- Sets X and Y to 0

//@mfunc 	| SRGCoordinate |~SRGCoordinate | Destructor

//@mfunc 	void | SRGCoordinate | SetX | Sets the floating point X coordinate

//@mfunc 	void | SRGCoordinate | SetX | Sets the floating point X coordinate from a double

//@mfunc 	void | SRGCoordinate | SetX | Sets the floating point X coordinate from an integer

//@mfunc 	float | SRGCoordinate | GetX | Returns the floating point X coordinate

//@mfunc 	void | SRGCoordinate | SetY | Sets the floating point Y coordinate

//@mfunc 	void | SRGCoordinate | SetY | Sets the floating point Y coordinate from a double

//@mfunc 	void | SRGCoordinate | SetY | Sets the floating point Y coordinate from an integer

//@mfunc 	float | SRGCoordinate | GetY | Returns the floating point Y coordinate

//@class SRGCoordinate | Manages a single floating point coordinate pair -- used for scaleable polygons
class SRGCoordinate
{
//@access public data members
public:

	//@cmember
	/* X coordinate*/
	float x;
	//@cmember
	/* Y coordinate*/
	float y;

//@access public member functions
public:
	//@cmember
	/* Initializing constructor -- sets X and Y to 0*/
	SRGCoordinate(){x=y=0.0f;}
	//@cmember
	/* Destructor*/
	virtual ~SRGCoordinate(){};
	//@cmember
	/* Sets the floating point X coordinate*/
	virtual void SetX(float f){x=f;}
	//@cmember
	/* Sets the floating point X coordinate*/
	virtual void SetX(double f){x=(float)f;}
	//@cmember
	/* Sets the floating point X coordinate*/
	virtual void SetX(int f){x=(float)f;}
	//@cmember
	/* Returns the floating point X coordinate*/
	virtual float GetX(){return x;}
	//@cmember
	/* Sets the floating point Y coordinate*/
	virtual void SetY(float f){y=f;}
	//@cmember
	/* Sets the floating point Y coordinate*/
	virtual void SetY(double f){y=(float)f;}
	//@cmember
	/* Sets the floating point Y coordinate*/
	virtual void SetY(int f){y=(float)f;}
	//@cmember
	/* Returns the floating point Y coordinate*/
	virtual float GetY(){return y;}
};


//////////////////////////////////////////////////////
//  Autoduck comment block for SRGCompiledPolygon
//
//@doc SRGCompiledPolygon

//@mdata CString | SRGCompiledPolygon | m_strName | Name of the polygon

//@mdata LPPOINT | SRGCompiledPolygon | m_pPoints | Pointer to the list of CPoints which is 
//generated by compiling the floating point coodinates

//@mdata int | SRGCompiledPolygon | m_nCount | Number of CPoint objects in the list pointed to by m_pPoints<nl>
//Note that this may be different from the number of points in the floating point coordinate list.

//@mdata CPtrList | SRGCompiledPolygon | m_Coords | Linked list of SRGCoordinate objects -- 
//one for each point in the polygon<nl>
//By storing the coordinates as floating point data, the scaling and positioning of graphic 
//shapes may be carried out with great accuracy.

//@mdata BOOL | SRGCompiledPolygon | m_bDirty | Indicates that the floating point list must be recompiled<nl>
//As floating point coordinates are added to the list, the integer CPoint list will become out of date. 

//@mfunc int | SRGCompiledPolygon | GetCount | Returns the number of points or SRGCoordinates used to describe this polygon

//@doc SRGCompiledPolygon
//@mdata double  | SRGCompiledPolygon | m_dScaleY | The Y scale of the polygon, normally 1.0

//@doc SRGCompiledPolygon
//@mdata double  | SRGCompiledPolygon | m_dScaleX | The X scale of the polygon. Normally 1.0


//@doc SRGCompiledPolygon
//@mdata BOOL  | SRGCompiledPolygon | m_bRotated | Set to TRUE if that polygon is to be rotated.

//@doc SRGCompiledPolygon
//@mdata double  | SRGCompiledPolygon | m_dRotation | The angle, in degrees, to which the polygon should be rotated.

//@doc SRGCompiledPolygon
//@mfunc virtual void  | SRGCompiledPolygon | SetScaleY | Sets the Y scale of the polygon 
//@parm double  | v | The relative scale: 1.0 for 1:1 scale, less than 1 for smaller, greater than 1 for bigger


//@doc SRGCompiledPolygon
//@mfunc virtual double  | SRGCompiledPolygon | GetScaleY | Returns the Y scale of the polygon. 


//@doc SRGCompiledPolygon
//@mfunc virtual void  | SRGCompiledPolygon | SetScaleX | Sets the X scale of the polygon 
//@parm double  | v | The relative scale: 1.0 for 1:1 scale, less than 1 for smaller, greater than 1 for bigger


//@doc SRGCompiledPolygon
//@mfunc virtual double  | SRGCompiledPolygon | GetScaleX | Returns the current polygon X scale. 


//@doc SRGCompiledPolygon
//@mfunc virtual void  | SRGCompiledPolygon | SetRotated | Sets the rotation semaphore 
//@parm BOOL  | v | TRUE to signify rotation. 


//@doc SRGCompiledPolygon
//@mfunc virtual BOOL  | SRGCompiledPolygon | GetRotated | Gets the rotation semaphore 


//@doc SRGCompiledPolygon
//@mfunc virtual void  | SRGCompiledPolygon | SetRotation | Sets the number of degrees of rotation 
//@parm double  | v | Rotation angle in degrees. 


//@doc SRGCompiledPolygon
//@mfunc virtual double  | SRGCompiledPolygon | GetRotation | Gets the number of degrees of rotation 


//adinsert

//@topic SRGCompiledPolygon Class Overview |
//This class manages a polygon which is stored as a list of floating point coordinates. When needed the floting point list is compiled into an integer list with scalingm rotation and offset already applied.

//@class Manages a single scaleable polygon object
//@devnote When repeated movement, scaling, or other operations are carried 
//out on polygons, the coordinates may become degraded through small computational 
//inaccuraccies and the polygon may become malformed. By keeping a pristine floating point 
//"master list" of points and generating a compiled CPoint-list polygon from the master every time 
//an operation takes place, the polygon will always be an accurate representation of the original.
class SRGCompiledPolygon : public CObject
{
//@access protected data members
protected:
	//@cmember
	/* The Y scaling factor*/
	double m_dScaleY;
	//@cmember
	/* The X scaling factor*/
	double m_dScaleX;
	//@cmember
	/* The rotation semaphore*/
	BOOL m_bRotated;
	//@cmember
	/* The angle of rotation.*/
	double m_dRotation;
	//@cmember
	/* Assigns or reassigns required memory*/
	virtual void AssignPointBlock();
	//@cmember
	/* Name of the polygon or wiget*/
	CString m_strName;
	//@cmember
	/* List of CPoint points*/
	LPPOINT m_pPoints;
	//@cmember
	/* Number of points in the integer polygon*/
	int m_nCount;
	//@cmember
	/* List of the floating point coordinates*/
	CPtrList m_Coords;
	//@cmember
	/* Semaphore indicating that the polygon should be recompiled */
	BOOL m_bDirty;
	

//@access public member functions
public:
	//@cmember
	/* Initialises the Y scaling factor*/
	virtual void SetScaleY(double v){m_dScaleY=v;}
	//@cmember
	/* Gets the Y scaling factor*/
	virtual double GetScaleY(){return m_dScaleY;}
	//@cmember
	/* Initialises the X scaling factor*/
	virtual void SetScaleX(double v){m_dScaleX=v;}
	//@cmember
	/* Gets the X scaling factor*/
	virtual double GetScaleX(){return m_dScaleX;}
	//@cmember
	/* Sets the rotation semaphore*/
	virtual void SetRotated(BOOL v){m_bRotated=v;}
	//@cmember
	/* Gets the rotation semaphore*/
	virtual BOOL GetRotated(){return m_bRotated;}
	//@cmember
	/* Sets the rotation angle*/
	virtual void SetRotation(double v){m_dRotation=v;}
	//@cmember
	/* Gets the rotation angle*/
	virtual double GetRotation(){return m_dRotation;}
	//@cmember
	/* Gets the	number of CPoints in the list.*/
	int GetIntegerPointCount();
	//@cmember
	/* Adds points to create a circle with (nPoints) nodes.*/
	virtual void AddCirclePoints(int nPoints);
	//@cmember
	/* Constructs a polygon with a stock shape.*/
	SRGCompiledPolygon(int nPrimitive);
	//@cmember
	/* Sets the rotation to the specified angle.*/
	virtual void RotatePoints(double dDegrees,LPRECT pRect=NULL);
	//@cmember
	/* Converts the floating point list into a CPoint list which is scaled to fit neatly into the desired rectangle*/
	virtual LPPOINT GetFittedPoints(CRect &r);
	//@cmember
	/* Generates a CPoint list to be an integer representation of the floating point list with X and Y offsets added*/
	virtual void OffsetPolygon(float xo,float yo);
	//@cmember
	/* Returns the name of this polygon*/
	virtual CString & GetName();
	//@cmember
	/* Initializes the name of this polygon*/
	virtual void SetName(LPCTSTR name);
	//@cmember
	/* Constructor*/
	SRGCompiledPolygon();
	//@cmember
	/* Virtual Destructor*/
	virtual ~SRGCompiledPolygon();
	//@cmember
	/* Returns a pointer to the integer (compiled) point block*/
	virtual LPPOINT GetPoints();
	//@cmember
	/* Adds a floating point coordinate pair to the list*/
	virtual void AddCoord(SRGCoordinate *c);
	//@cmember
	/* Adds a coordinate pair using floats*/
	virtual void AddCoord(float xc,float yc);
	//@cmember
	/* Adds a coordinate pair using integers*/
	virtual void AddCoord(int nx,int ny);
	//@cmember
	/* Returns the number of points in the floating point list*/
	virtual int GetCount(){return m_Coords.GetCount();}
};


#endif

// Reset DLL declaration context

#undef AFX_DATA
#define AFX_DATA
#undef AFXAPP_DATA
#define AFXAPP_DATA NEAR

